Add functionality of AI Tutor
edly-io/ai-feedback-xblock pull request #1
Opened 2023-06-07 06:06 UTC by hinakhadim

Add functionality of AI Tutor

2023-06-07 07:08 UTC, ziafazal requested changes
@hinakhadim thanks for creating this PR. I have some suggestions.

2023-06-07 07:08 UTC, ziafazal commented on ai_tutor/ai_tutor.py
> +    is_allowed_for_coach_help = Boolean(default=True, scope=Scope.user_state,
I think we need two fields one to count number of times learner has asked for review and other fields to set a threshold of how many times review can be asked.

2023-06-07 07:08 UTC, ziafazal commented on ai_tutor/ai_tutor.py
> +    description = String(
where is this `description` is going to be used?

2023-06-07 07:08 UTC, ziafazal commented on ai_tutor/ai_tutor.py
> +class AITutorXBlock(XBlock, StudioEditableXBlockMixin):
Inherit it from `CompletableXBlockMixin` and then add
`self.emit_completion(1.0)` inside `submit_answer` method to mark block completion

2023-06-07 07:08 UTC, ziafazal commented on ai_tutor/ai_tutor.py
> +                prompt=prompt, model=model, temperature=temperature, max_tokens=max_tokens, n=n)
How `max_tokens` and `n` is going to effect the response?

2023-06-07 07:08 UTC, ziafazal commented on setup.py
> +        'XBlock',
`openai` should be in the dependencies of this xblock

2023-06-07 07:08 UTC, ziafazal commented on setup.py
> +    name='ai_tutor-xblock',
We should be consistent with name of xblock everywhere in the code and files names. what if we use `ai_coach` everywhere?

2023-06-07 07:08 UTC, ziafazal commented on setup.py
> +    license='UNKNOWN',          # TODO: choose a license: 'AGPL v3' and 'Apache 2.0' are popular.
`AGPL v3` should be fine here.

2023-06-08 07:27 UTC, hinakhadim commented on ai_tutor/ai_tutor.py
> +                prompt=prompt, model=model, temperature=temperature, max_tokens=max_tokens, n=n)
`max_tokens` is the maximum number of [tokens](https://platform.openai.com/tokenizer) to generate in the completion. Tokens are created from words or common sequences of characters found in text.  `The more the number of token, the more detailed the response is (or response has more words)`

`n` is how many responses will be returned by model.  For example, if ` n= 1` we give prompt='I live in` . It returns [`I live in Lahore`]. but if `n=2`, it returns ['I live in lahore', 'I live in Karachi'] (2 responses). `Warning: The more the value of n, the more it consume your token quota  quickly`.

For detailed information, [OPEN AI Documentation](https://platform.openai.com/docs/api-reference/completions/create)

2023-06-08 07:27 UTC, hinakhadim commented on ai_tutor/ai_tutor.py
> +    description = String(
The description isn't using anywhere. I created it for if admin wants to store some extra information (regarding question or answer) for himself.

2023-06-08 09:04 UTC, ziafazal requested changes
@hinakhadim thanks for addressing feedback its almost there just few minor things to look into.

2023-06-08 09:04 UTC, ziafazal commented on setup.py
> +    name='ai_coach-xblock',
name should be `ai-coach-xblock`

2023-06-08 09:04 UTC, ziafazal commented on setup.py
> +    description='ai_coach XBlock',
Description should be `AI Coach Xblock evaluates open response answer of a question using Open AI`
and add Long Description should pulled from readme like [this](https://github.com/edly-io/h5pxblock/blob/master/setup.py#L33)

2023-06-08 09:04 UTC, ziafazal commented on README.md
> +## AI Tutor XBlock
Can we add little description of what this xblock does and possible use cases? Also we should add few screenshots of xblock(in studio and LMS) like [this](https://github.com/edly-io/h5pxblock#readme)

2023-06-09 06:40 UTC, ziafazal approved these changes
LGTM

2023-06-09 06:41 UTC, merged